import { setLoading } from './milestoneAction';

export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_MILESTONES = 'GET_MILESTONES';
export const ADD_MILESTONE = 'ADD_MILESTONE';
export const UPDATE_MILESTONE = 'UPDATE_MILESTONE';
export const DELETE_MILESTONE = 'DELETE_MILESTONE';
export const SET_CURRENT_MILESTONE = 'SET_CURRENT_MILESTONE';
export const CLEAR_CURRENT_MILESTONE = 'CLEAR_CURRENT_MILESTONE';
export const MILESTONE_ERROR = 'MILESTONE_ERROR';
export const SEARCH_MILESTONE = 'SEARCH_MILESTONE';

export const GET_EXPENDITURES = 'GET_EXPENDITURES';
export const ADD_EXPENDITURE = 'ADD_EXPENDITURE';
export const UPDATE_EXPENDITURE = 'UPDATE_EXPENDITURE';
export const DELETE_EXPENDITURE = 'DELETE_EXPENDITURE';
export const SET_CURRENT_EXPENDITURE = 'SET_CURRENT_EXPENDITURE';
export const CLEAR_CURRENT_EXPENDITURE = 'CLEAR_CURRENT_EXPENDITURE';
export const EXPENDITURE_ERROR = 'EXPENDITURE_ERROR';
export const SEARCH_EXPENDITURE = 'SEARCH_EXPENDITURE';